apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: production
data:
  application-prod.yml: |
    spring:
      application:
        name: csv-consumer-service

    server:
      port: 8082
  
    
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true