apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: production
data:
  application-prod.yml: |
    spring:
      application:
        name: csv-consumer-service
      kafka:
        bootstrap-servers: kafka-service:9092
        consumer:
          group-id: csv-consumer-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "*"
        properties:
          enable.auto.commit: false
      datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
      h2:
        console:
          enabled: true
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
    
    server:
      port: 8082
    
    kafka:
      topic:
        csv-data: pessoas-topic
    
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true