apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: production
data:
  application-prod.yml: |
    spring:
      application:
        name: csv-consumer-service
      kafka:
        bootstrap-servers: kafka-service:9092
        consumer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring.json.add.type.headers: false
        properties:
          acks: all
          retries: 3

    server:
      port: 8081

    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true