apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: production
  labels:
    app: consumer-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082
      protocol: TCP
      name: http
  selector:
    app: consumer-service